### ISSUE TITLE
Facebook connect cannot create user because there is no password

### ISSUE THREAD

**Issue by kmergen** [dektrium/yii2-user#1034]
### What steps will reproduce the problem?
facebook connect account
### What is the expected result?
Create User in user table
### What do you get instead?
`
PDOException: SQLSTATE[HY000]: General error: 1364 Field 'password_hash' doesn't have a default value in C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Command.php:1258
Stack trace:
#0 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Command.php(1258): PDOStatement->execute()
#1 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `us...')
#2 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Schema.php(433): yii\db\Command->execute()
#3 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\ActiveRecord.php(549): yii\db\Schema->insert('{{%user}}', Array)
#4 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\ActiveRecord.php(515): yii\db\ActiveRecord->insertInternal(NULL)
#5 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 C:\www\hundekauf-yii2\vendor\dektrium\yii2-user\models\User.php(279): yii\db\BaseActiveRecord->save()
#7 C:\www\hundekauf-yii2\vendor\dektrium\yii2-user\controllers\RegistrationController.php(179): dektrium\user\models\User->create()
#8 [internal function]: dektrium\user\controllers\RegistrationController->actionConnect('VJATewJoJFt6N6s...')
#9 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#10 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('connect', Array)
#12 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('user/registrati...', Array)
#13 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 C:\www\hundekauf-yii2\frontend\web\index.php(17): yii\base\Application->run()
#15 {main}

Next yii\db\Exception: SQLSTATE[HY000]: General error: 1364 Field 'password_hash' doesn't have a default value
The SQL being executed was: INSERT INTO `user` (`username`, `email`, `auth_key`, `registration_ip`, `created_at`, `updated_at`) VALUES ('Mariechen', 'vnmefgdpvt_1528962028@tfbnw.net', 'TlPoSKqGqXX1il0w5KxWqCtgXF-HnAy3', '127.0.0.1', 1528964073, 1528964073) in C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Schema.php:664
Stack trace:
#0 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'INSERT INTO `us...')
#1 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Command.php(1075): yii\db\Command->internalExecute('INSERT INTO `us...')
#2 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\Schema.php(433): yii\db\Command->execute()
#3 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\ActiveRecord.php(549): yii\db\Schema->insert('{{%user}}', Array)
#4 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\ActiveRecord.php(515): yii\db\ActiveRecord->insertInternal(NULL)
#5 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\db\BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#6 C:\www\hundekauf-yii2\vendor\dektrium\yii2-user\models\User.php(279): yii\db\BaseActiveRecord->save()
#7 C:\www\hundekauf-yii2\vendor\dektrium\yii2-user\controllers\RegistrationController.php(179): dektrium\user\models\User->create()
#8 [internal function]: dektrium\user\controllers\RegistrationController->actionConnect('VJATewJoJFt6N6s...')
#9 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#10 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('connect', Array)
#12 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('user/registrati...', Array)
#13 C:\www\hundekauf-yii2\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 C:\www\hundekauf-yii2\frontend\web\index.php(17): yii\base\Application->run()
#15 {main}
Additional Information:
Array
(
    [0] => HY000
    [1] => 1364
    [2] => Field 'password_hash' doesn't have a default value
)

Copy Stacktrace Search Stackoverflow Search Google Exception
Database Exception – yii\db\Exception
SQLSTATE[HY000]: General error: 1364 Field 'password_hash' doesn't have a default value
The SQL being executed was: INSERT INTO `user` (`username`, `email`, `auth_key`, `registration_ip`, `created_at`, `updated_at`) VALUES ('Mariechen', 'vnmefgdpvt_1528962028@tfbnw.net', 'TlPoSKqGqXX1il0w5KxWqCtgXF-HnAy3', '127.0.0.1', 1528964073, 1528964073)`
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version  2.0.14    |
| Yii2-user version 0.9.dev |
| PHP version 7.0.22      |

**Comment by ServerDotBiz** [comment]
I just noticed the same error in our logs, any idea what might cause this?
