### ISSUE TITLE
Yii2 Advanced + Dektrum db migration errors.

### ISSUE THREAD

**Issue by bizilliam** [dektrium/yii2-user#598]
I can't get dektrium to migrate/update properly per installation/configuration instructions.  backed up db before trying.  migrate failed.  deleted all tables 'drop table "user";', etc.. tried again, then getting different token errors.

Restored db to pre-dektrium and back at this.  Has anyone tried to migration from a clean Yii2 Advanced install lately?

$ php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations
Yii Migration Tool (based on Yii v2.0.6)

Total 7 new migrations to be applied:
        m140209_132017_init
        m140403_174025_create_account_table
        m140504_113157_update_tables
        m140504_130429_create_token_table
        m140830_171933_fix_ip_field
        m140830_172703_change_account_table_name
        m141222_110026_update_ip_field

Apply the above migrations? (yes|no) [no]:yes
*** applying m140209_132017_init
    > create table {{%user}} ...Exception 'yii\db\Exception' with message 'SQLSTATE[42P07]: Duplicate table: 7 ERROR:  relation "user" already exists
The SQL being executed was: CREATE TABLE "user" (
        "id" serial NOT NULL PRIMARY KEY,
        "username" varchar(25) NOT NULL,
        "email" varchar(255) NOT NULL,
        "password_hash" varchar(60) NOT NULL,
        "auth_key" varchar(32) NOT NULL,
        "confirmation_token" varchar(32),
        "confirmation_sent_at" integer,
        "confirmed_at" integer,
        "unconfirmed_email" varchar(255),
        "recovery_token" varchar(32),
        "recovery_sent_at" integer,
        "blocked_at" integer,
        "registered_from" integer,
        "logged_in_from" integer,
        "logged_in_at" integer,
        "created_at" integer NOT NULL,
        "updated_at" integer NOT NULL
)'

in /var/www/vendor/yiisoft/yii2/db/Schema.php:628

Error Info:
Array
(
    [0] => 42P07
    [1] => 7
    [2] => ERROR:  relation "user" already exists
)

Stack trace:
#0 /var/www/vendor/yiisoft/yii2/db/Command.php(791): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE "u...')
#1 /var/www/vendor/yiisoft/yii2/db/Migration.php(260): yii\db\Command->execute()
#2 /var/www/vendor/dektrium/yii2-user/migrations/m140209_132017_init.php(40): yii\db\Migration->createTable('{{%user}}', Array, NULL)
#3 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(492): m140209_132017_init->up()
#4 /var/www/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(129): yii\console\controllers\BaseMigrateController->migrateUp('m140209_132017_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(0)
#6 /var/www/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /var/www/vendor/yiisoft/yii2/base/Controller.php(151): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/vendor/yiisoft/yii2/console/Controller.php(91): yii\base\Controller->runAction('up', Array)
#9 /var/www/vendor/yiisoft/yii2/base/Module.php(455): yii\console\Controller->runAction('up', Array)
#10 /var/www/vendor/yiisoft/yii2/console/Application.php(167): yii\base\Module->runAction('migrate/up', Array)
#11 /var/www/vendor/yiisoft/yii2/console/Application.php(143): yii\console\Application->runAction('migrate/up', Array)
#12 /var/www/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /var/www/yii(27): yii\base\Application->run()
#14 {main}

**Comment by bizilliam** [comment]
For some strange reason I kept dropping tables, dropp tables, but "user" really wasn't deleted.  After a fresh start, migrate worked properly.  I also saw some dektrium forums, I'll post there next time.  Closing issue 'issue'.
