### ISSUE TITLE
Error on reverted migration

### ISSUE THREAD

**Issue by goffyara** [dektrium/yii2-user#747]
### What steps will reproduce the problem?
Using postgresql 9.5
```bash
php yii migrate/up --migrationPath=@vendor/dektrium/yii2-user/migrations
php yii migrate/down 10 --migrationPath=@vendor/dektrium/yii2-user/migrations
```
### What is the expected result?
```
Total 10 migration to be reverted...bla bla
```
### What do you get instead?
```
*** reverting m141222_110026_update_ip_field
    > alter column registration_ip in table {{%user}} to bigint ...Exception 'yii\db\Exception' with message 'SQLSTATE[42804]: Datatype mismatch: 7 ERROR:  column "registration_ip" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING registration_ip::bigint".
The SQL being executed was: ALTER TABLE "user" ALTER COLUMN "registration_ip" TYPE bigint'

in /data/sites/bb_crm_b/vendor/yiisoft/yii2/db/Schema.php:633

Error Info:
Array
(
    [0] => 42804
    [1] => 7
    [2] => ERROR:  column "registration_ip" cannot be cast automatically to type bigint
HINT:  You might need to specify "USING registration_ip::bigint".
)

Stack trace:
#0 /data/sites/bb_crm_b/vendor/yiisoft/yii2/db/Command.php(852): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE "us...')
#1 /data/sites/bb_crm_b/vendor/yiisoft/yii2/db/Migration.php(364): yii\db\Command->execute()
#2 /data/sites/bb_crm_b/vendor/dektrium/yii2-user/migrations/m141222_110026_update_ip_field.php(53): yii\db\Migration->alterColumn('{{%user}}', 'registration_ip', 'bigint')
#3 /data/sites/bb_crm_b/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(537): m141222_110026_update_ip_field->down()
#4 /data/sites/bb_crm_b/vendor/yiisoft/yii2/console/controllers/BaseMigrateController.php(191): yii\console\controllers\BaseMigrateController->migrateDown('m141222_110026_...')
#5 [internal function]: yii\console\controllers\BaseMigrateController->actionDown(10)
#6 /data/sites/bb_crm_b/vendor/yiisoft/yii2/base/InlineAction.php(55): call_user_func_array(Array, Array)
#7 /data/sites/bb_crm_b/vendor/yiisoft/yii2/base/Controller.php(154): yii\base\InlineAction->runWithParams(Array)
#8 /data/sites/bb_crm_b/vendor/yiisoft/yii2/console/Controller.php(119): yii\base\Controller->runAction('down', Array)
#9 /data/sites/bb_crm_b/vendor/yiisoft/yii2/base/Module.php(454): yii\console\Controller->runAction('down', Array)
#10 /data/sites/bb_crm_b/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/down', Array)
#11 /data/sites/bb_crm_b/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('migrate/down', Array)
#12 /data/sites/bb_crm_b/vendor/yiisoft/yii2/base/Application.php(375): yii\console\Application->handleRequest(Object(yii\console\Request))
#13 /data/sites/bb_crm_b/yii(20): yii\base\Application->run()
#14 {main}
```
### Additional info

| Q                 | A
| ----------------- | ---
| Yii2 version      | 2.0.9
| Yii2-user version | 0.9.6
| PHP version       | 7.0.9-1

**Comment by dmeroff** [comment]
Fixed.
