### ISSUE TITLE
Error authorization through social network VK

### ISSUE THREAD

**Issue by ankkk** [dektrium/yii2-user#809]
Some users are unable to log in. In the logs is this:

```
2016-11-30 17:35:08 [12.34.56.78][345062][jr7854kb94ubom7bje6s03u3q2][error][yii\web\HttpException:404] yii\base\InvalidRouteException: Unable to resolve the request "null". in /var/www/html/cash4real/vendor/yiisoft/yii2/base/Module.php:460
Stack trace:
#0 /var/www/html/site/vendor/yiisoft/yii2/web/Application.php(87): yii\base\Module->runAction('null', Array)
#1 /var/www/html/site/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#2 /var/www/html/site/web/index.php(15): yii\base\Application->run()
#3 {main}

Next yii\web\NotFoundHttpException: Page not found. in /var/www/html/site/vendor/yiisoft/yii2/web/Application.php:99
Stack trace:
#0 /var/www/html/site/vendor/yiisoft/yii2/base/Application.php(375): yii\web\Application->handleRequest(Object(yii\web\Request))
#1 /var/www/html/site/web/index.php(15): yii\base\Application->run()
#2 {main}
```

In config/web.php:
```php
Event::on(SecurityController::class, SecurityController::EVENT_AFTER_AUTHENTICATE, function (AuthEvent $e) {
    // if user account was not created we should not continue
    if ($e->account->user === null) {
        return;
    }

    // we are using switch here, because all networks provide different sets of data
    $i = $e->client->getName();
    $email = (!empty($e->client->getUserAttributes()['email'])) ? $e->client->getUserAttributes()['email'] : null;
    $bridthday = (!empty($e->client->getUserAttributes()['bdate'])) ? date('Y-m-d', strtotime($e->client->getUserAttributes()['bdate'])) : null;
    $sex = (!empty($e->client->getUserAttributes()['sex'])) ? $e->client->getUserAttributes()['sex'] : null;
    $tz = (!empty($e->client->getUserAttributes()['timezone'])) ? $e->client->getUserAttributes()['timezone'] : null;
    if ($i == 'vkontakte') {
        $e->account->user->profile->updateAttributes([
            'name' => $e->client->getUserAttributes()['first_name'] . ' ' . $e->client->getUserAttributes()['last_name'],
            'public_email' => $email,
            'sex' => $sex,
            'bridthday' => $bridthday,
            'timezone' => $tz,
            'avatar' => $e->client->getUserAttributes()['photo'],
        ]);
    }

    // after saving all user attributes will be stored under account model
    // Yii::$app->identity->user->accounts['facebook']->decodedData
});
```
And users "user_id" is not present in social_account
![Problem](http://i.imgur.com/gMeuAZZ.png)

What could be the reason?

**Comment by dmeroff** [comment]
Please note, that the GitHub Issue Tracker is for bug reports and feature requests only.

We are happy to help you on the [support forum](https://dektrium.com). Please use it to discuss the problem.

If the result of the discussion turns out that there really is a bug in the extension, feel free to
come back and provide information on how to reproduce the issue. This issue will be closed for now.
