### ISSUE TITLE
Please make Finder overridable via DIC

### ISSUE THREAD

**Issue by danaki** [dektrium/yii2-user#854]
I have a legacy app and migrating to yii2. The problem that there're no DB entities like User or Profile, but a simple REST API to an external service with it's own database.

I've tried to override models in order to make them call the REST instead of doing DB queries. I followed the "Overriding models" tutorial, but it seems that Finder is hardly binded to ActiveQuery and there're no possibility to override it. I've tried to replace \dektrium\user\Finder via DIC configuration via 'containers' config option made available in 2.0.11 but without success (because of the order of DIC initialization). I also tried to make yii2-user a nested module of my own in order to override the DIC values set in Bootstrap::bootstrap() but was unable to make routing work. The most successful attempt was to create another module like 'user2' and put it to 'modules' in config just under 'yii-user' to make it sure it will innitialize immediately after it and replace your Finder to mine, with find* methods overriden, like so:
```php
<?php

namespace frontend\modules\user2;

use Yii;
use yii\base\BootstrapInterface;
use yii\base\Module as BaseModule;

class Module extends BaseModule implements BootstrapInterface
{
    public function bootstrap($app)
    {
        Yii::$container->set(\dektrium\user\Finder::className(), Finder::className());
    }
}

```

but now I've got an error like so:
```
Exception 'TypeError' with message 'Argument 3 passed to dektrium\user\controllers\RegistrationController::__construct() must be an instance of dektrium\user\Finder, instance of frontend\modules\user2\Finder given' 

in /www/front.dev/vendor/dektrium/yii2-user/controllers/RegistrationController.php:94

Stack trace:
#0 [internal function]: dektrium\user\controllers\RegistrationController->__construct('registration', Object(dektrium\user\Module), Object(frontend\modules\user2\Finder), Array)
#1 /www/front.dev/vendor/yiisoft/yii2/di/Container.php(373): ReflectionClass->newInstanceArgs(Array)
#2 /www/front.dev/vendor/yiisoft/yii2/di/Container.php(154): yii\di\Container->build('dektrium\\user\\c...', Array, Array)
...
```

I suggest to make 2 updates:
 * Create a FinderInterface for users who want to implement Finder API of their own.
 * Make Finder a configurable DIC config value in order to override it like you do for 'modelMap'
 * Don't bind to dektrium\user\Finder type in RegistrationController etc but to an instance of FinderInterface

Thanks.

**Comment by niciz** [comment]
same problem here!
