### ISSUE TITLE
migration failure > 0.9.12

### ISSUE THREAD

**Issue by chmig29fulcrum** [dektrium/yii2-user#867]
Yii 2.0.2 PHP 5.5.11
Getting error while migrating UP

```
D:\Work\XAMPP\htdocs\a1.com>php yii migrate/up --migrationPath=@vendor/dektrium/y
ii2-user/migrations
Yii Migration Tool (based on Yii v2.0.2)

Total 6 new migrations to be applied:
        m141222_110026_update_ip_field
        m141222_135246_alter_username_length
        m150614_103145_update_social_account_table
        m150623_212711_fix_username_notnull
        m151218_234654_add_timezone_to_profile
        m160929_103127_add_last_login_at_to_user_table

Apply the above migrations? (yes|no) [no]:y
*** applying m141222_110026_update_ip_field
Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method
: m141222_110026_update_ip_field::string()'

in D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\base\Component.php:282

Stack trace:
#0 D:\Work\XAMPP\htdocs\a1.com\vendor\dektrium\yii2-user\migrations\m141222_11002
6_update_ip_field.php(23): yii\base\Component->__call('string', Array)
#1 D:\Work\XAMPP\htdocs\a1.com\vendor\dektrium\yii2-user\migrations\m141222_11002
6_update_ip_field.php(23): m141222_110026_update_ip_field->string(45)
#2 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\console\controllers\BaseMigrat
eController.php(489): m141222_110026_update_ip_field->up()
#3 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\console\controllers\BaseMigrat
eController.php(126): yii\console\controllers\BaseMigrateController->migrateUp('
m141222_110026_...')
#4 [internal function]: yii\console\controllers\BaseMigrateController->actionUp(
0)
#5 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\base\InlineAction.php(55): cal
l_user_func_array(Array, Array)
#6 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\base\Controller.php(178): yii\
base\InlineAction->runWithParams(Array)
#7 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\console\Controller.php(91): yi
i\base\Controller->runAction('up', Array)
#8 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\base\Module.php(455): yii\cons
ole\Controller->runAction('up', Array)
#9 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\console\Application.php(161):
yii\base\Module->runAction('migrate/up', Array)
#10 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\console\Application.php(137):
 yii\console\Application->runAction('migrate/up', Array)
#11 D:\Work\XAMPP\htdocs\a1.com\vendor\yiisoft\yii2\base\Application.php(375): yi
i\console\Application->handleRequest(Object(yii\console\Request))
#12 D:\Work\XAMPP\htdocs\a1.com\yii(23): yii\base\Application->run()
#13 {main}
```

**Comment by chmig29fulcrum** [comment]
problem was with old version of yii2 2.0.2
upgrading to new version solved the problem.

**Comment by MarioPerez92** [comment]
Hello, I decided to create a new database, without tables. Then change the name of the database to: C: \ wamp64 \ www \ advanced \ common \ config \ main-local.php And run the commands: yii migrate / up --migrationPath = @ vendor / dektrium / yii2-user / migrations. Good day.
